#!/usr/bin/env fish

set list ./sources/works.txt
set frogs beavis.zen blowfish bong bud-frogs bunny cheese cower daemon default dragon dragon-and-cow elephant elephant-in-snake eyes flaming-sheep ghostbusters head-in hellokitty kiss kitty koala kosh luke-koala meow milk moofasa moose mutilated ren satanic sheep skeleton small stegosaurus stimpy supermilker surgery three-eyes turkey turtle tux udder vader vader-koala www
set works (cat $list)
set piece (random 1 (count $works))
set frog (random 1 (count $frogs))

clear
cowsay -f $frogs[$frog] "Next, I will be showing you the work $works[$piece]"
espeak "Next, I will be showing you the work $works[$piece]."
